import streamlit as st
st.title("Trinity Baseball Tigermetrics")
st.markdown("Welcome to the Trinity University Baseball Tigermetrics Lab! See the below sections for page guides.")
st.markdown("---")

st.header("Pitcher Breakdowns")
st.subheader("Pitch Log")
st.markdown("The Pitch Log allows for easy viewing of different metrics pitch-by-pitch. To start, select a pitcher and date range, then select your desired metrics to display from the dropdown menu.")
st.subheader("Visualizations Guide")
st.markdown("Metrics by Pitch Type")
st.markdown("This section shows overall key metrics for each pitch type (# of tracked pitches, average/max velo, etc). See the note below the table on the Pitcher Breakdowns page.")
st.subheader("Visualizations")
st.markdown("This section contains three different graphics: A strike zone spray chart, movement chart, and violin chart. The violin chart shows the distribution of pitch velocities over different sessions as well as how the average velocity changes over time.")
st.markdown("")
st.markdown("I am also planning to add a feature in the future that allows comparisons between two pitchers.")
st.markdown("---")

st.header("Game Charts")
st.markdown("WORK IN PROGRESS---This section is planned to become operational once the pitching outcomes tool is built. It will show at-bats pitch by pitch across an outing.")
st.markdown("---")

st.header("Matchups")
st.markdown("WORK IN PROGRESS---This section is planned to show matchup data for pitchers against hitters.")
st.markdown("Examples: What is x pitcher's BAA when throwing sliders to left-handed hitters? How often is x pitcher's fastball put in play when he throws it middle-in?")
st.markdown("---")

st.header("Matrix")
st.markdown("WORK IN PROGRESS---This section will contain a matrix of probabilities for each pitcher showing the likelihoods of different outcomes in different situations. I will add options to display different statistics.")
st.subheader("Example matrix for run probability (Fictional Data)")
st.image("run_matrix_example.jpg")
st.markdown("---")

st.header("Stuff+")
st.markdown('This section ranks pitchers and their pitch types by average stuff+. As a reminder, stuff+ is a measure of how "nasty" a pitch is, calculated by using velocity, spin rate, and movement data. A stuff+ of 100 would be a perfectly average pitch relative to our staff, and a 120 would be 20 percent better than average.')
st.subheader("Average Stuff+ Leaderboard")
st.markdown("The top table shows average stuff+ values by pitcher and pitch type. It can be filtered by date, pitcher, handedness, pitch type, and number of pitches thrown (example: only display average stuff+ for pitches that have been thrown by a pitcher at least 10 times.)")
st.subheader("Top Individual Pitches Tracked")
st.markdown("The bottom table shows a ranking of individual pitches with the absolute highest recorded stuff+ values. This is also filterable.")
st.markdown("---")
st.header("Contact Information")
st.markdown("If you have any questions, need help, or have suggestions for additional features, please reach out to me.")
st.markdown("Phone: 281-381-0192")
st.markdown("Email: wgarrett@trinity.edu")